from utils.gradient_strategy.dct_generator import DCTGenerator
from utils.gradient_strategy.random_generator import RandomGenerator
from utils.gradient_strategy.centerconv_generator import CenterConvGenerator
from utils.gradient_strategy.upsample_generator import UpSampleGenerator